from typing import Final, List

EFF_WORDLIST: Final[List[str]] = [
    "a", "aah", "aahs", "aal", "aalii", "aaliis", "aals", "aardvark", "aardvarks", "aardwolf",
    "aardvark", "aardwolf", "abacus", "abalone", "abandon", "abbey", "abdomen", 
    "abduct", "abet", "ability", "ablaze", "able", "aboard", "abode", "aborigine",
    "abort", "above", "abrade", "abrasive", "abroad", "abrupt", "absent", "absorb",
    "abstract", "absurd", "abundance", "abundant", "abuse", "academy", "accelerate",
    "accent", "accept", "access", "accident", "acclaim", "accommodate", "accompany",
    "accomplish", "accord", "accordion", "account", "accuracy", "accurate", "accuse",
    "ace", "ache", "achieve", "acid", "acorn", "acoustic", "acquire", "acre",
    "acrobat", "across", "act", "action", "active", "actual", "ad", "adapt",
    "add", "addict", "addition", "address", "adequate", "adhere", "adjust", 
    "admire", "admission", "admit", "adobe", "adopt", "adult", "advance", 
    "advantage", "adventure", "adverse", "advertise", "advice", "advise", "aerial", 
    "affair", "affect", "afford", "afraid", "after", "again", "against", "age", 
    "agenda", "agent", "aggressive", "agree", "agreement", "agriculture", "ahead", 
    "aid", "aim", "air", "aircraft", "aisle", "alarm", "album", "alcohol", 
    "alert", "alibi", "alien", "align", "alike", "alive", "all", "allegation", 
    "alley", "alliance", "allocate", "allow", "allowance", "ally", "almost", 
    "alone", "along", "aloud", "alphabet", "already", "also", "alter", 
    "alternative", "although", "altitude", "altogether", "aluminum", "always", 
    "amaze", "ambassador", "ambiguous", "ambition", "ambulance", "amend", "amount", 
    "ample", "amuse", "analog", "analysis", "analyst", "analyze", "ancestor", 
    "anchor", "ancient", "and", "angel", "anger", "angle", "angry", 
    "animal", "ankle", "anniversary", "announce", "announcement", "annoy", "annual", 
    "another", "answer", "antenna", "antique", "anxiety", "any", "anybody", 
    "anyhow", "anyone", "anything", "anyway", "anywhere", "apartment", "apology", 
    "apparatus", "apparent", "appeal", "appear", "appearance", "appetite", "applaud", 
    "apple", "appliance", "applicant", "application", "apply", "appoint", "appointment", 
    "appreciate", "apprehend", "approach", "appropriate", "approval", "approve", "approximate",
    "april", "aptitude", "arc", "arch", "architect", "architecture", "area", 
    "arena", "argue", "argument", "arise", "arm", "army", "around", 
    "arrange", "arrangement", "arrest", "arrival", "arrive", "arrow", "art", 
    "article", "artificial", "artist", "ash", "aside", "ask", "asleep", 
    "aspect", "aspirin", "assault", "assemble", "assembly", "assert", "assess", 
    "asset", "assign", "assist", "assistance", "assistant", "associate", "association", 
    "assume", "assurance", "assure", "astronaut", "athlete", "atmosphere", "attach", 
    "attack", "attempt", "attend", "attention", "attitude", "attorney", "attract", 
    "attraction", "attribute", "auction", "audience", "audio", "audit", "august", 
    "aunt", "authority", "authorize", "auto", "automatic", "automobile", "auxiliary", 
    "available", "avenue", "average", "avoid", "await", "awake", "award", 
    "aware", "awareness", "away", "awful", "awkward", "axis", "baby",
]